class tubepress::packages {

  package {[
    'apt',
    'bash',
    'deborphan',
    'file',
    'git',
    'grep',
    'gzip',
    'lsof',
    'tar',
    'telnet',
    'unzip',
    'vim',
    'zip',
  ]:
    ensure => 'installed'
  }

  package {[
    'acpi',
    'acpi-support-base',
    'acpid',
    'apparmor',
    'apport',
    'apport-symptoms',
    'aptitude',
    'aptitude-common',
    'apt-listchanges',
    'at',
    'autopoint',
    'bc',
    'busybox',
    'byobu',
    'cloud-guest-utils',
    'cloud-init',
    'cloud-initramfs-rescuevol',
    'cloud-utils',
    'console-setup',
    'console-setup-linux',
    'db5.1-util',
    'dc',
    'debconf-i18n',
    'debian-faq',
    'discover',
    'discover-data',
    'doc-debian',
    'ed',
    'exim4*',
    'fontconfig',
    'fontconfig-config',
    'fonts-liberation',
    'fonts-ubuntu-font-family-console',
    'ftp',
    'fuse',
    'git-core',
    'heirloom-mailx',
    'host',
    'iamerican',
    'ibritish',
    'ienglish-common',
    'info',
    'installation-report',
    'iw',
    'juju',
    'mlocate',
    'mutt',
    'nano',
    'nfacct',
    'nfs-common',
    'popularity-contest',
    'ppp',
    'procmail',
    'reportbug',
    'rpcbind',
    'task-english',
    'tasksel',
    'tasksel-data',
    'texinfo',
    'traceroute',
    'ufw',
    'util-linux-locales',
    'w3m',
    'whoopsie',
    'x11-common',
    'xauth',
    'xserver-common',
  ]:
    ensure => 'purged'
  }

  exec { "apt-update":
    command => "/usr/bin/apt-get update",
    refreshonly => true,
  }

  apt::source { "precise-multiverse":
    location        => "http://archive.ubuntu.com/ubuntu",
    release         => "precise",
    repos           => "multiverse",
    include_src     => false,
    notify          => Exec['apt-update'],
  }

}