forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/apache'
mod 'puppetlabs/apt'
mod 'puppetlabs/inifile'
mod 'puppetlabs/mongodb'
mod 'puppetlabs/ntp'
mod 'puppetlabs/vcsrepo'

mod 'nodes/php', :git => 'git@github.com:jippi/puppet-php.git'

mod 'saz/timezone'
