#
# Copyright 2006 - 2016 TubePress LLC (http://tubepress.com)
# 
#  This file is part of TubePress (http://tubepress.com)
# 
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/apache'
mod 'puppetlabs/apt'
mod 'puppetlabs/inifile'
mod 'puppetlabs/mongodb'
mod 'puppetlabs/ntp'
mod 'puppetlabs/vcsrepo'

mod 'nodes/php', :git => 'git@github.com:jippi/puppet-php.git'

mod 'saz/timezone'
